import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Profile from '@/components/profile'
import Link from 'next/link'
import useSWR from 'swr'
import Tile from '@/components/tile'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })
let numOfItems = 12;

export const fetchFn = async (args:any) => {
  try {
  const res = await fetch(args)
  const data = await res.json()
  return data
  }
  catch (err) {
    console.error(err)
  }
}

export default function Home() {
  const { data, error, isLoading } = useSWR('https://jsonplaceholder.typicode.com/albums', fetchFn)

  const generateTiles = () => {
      if(data){
      const dataSample = data.slice(0, numOfItems)
     return dataSample.map((item: { id: number; title: string}) => <Tile key={item.id} title={item.title}/>)
    }
  }
  

  return (
    <>
      <Head>
        <title>Photux</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Header/>
        <div>
          {Profile() ? Profile() : ''}
          {generateTiles()}
           
        </div>
      </main>
    </>
  )
}
