import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Profile from '@/components/profile'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Photux </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {Profile() ? Profile() : ''}
           <Link href="/api/auth/login">Login</Link>
           <br/>
           <Link href="/api/auth/logout">Logout</Link>
        </div>
      </main>
    </>
  )
}
